### ISSUE TITLE
Provide full examples for config when integrated with FOS?

### ISSUE THREAD

**Issue by tcowin** [Maks3w/FR3DLdapBundle#10]
I'm trying to configure this with FOSUserBundle, and it would be helpful if you had complete examples for app/config/security.yml, config.yml and the User class as it would be with FR3D and FOS fully integrated... (especially in firewalls)

**Comment by hugo-aam** [comment]
Hi,
Can you confirm me this last bundle release is compatible with a 2.7.7 version of symfony ?
