### ISSUE TITLE
Enable / Disable config

### ISSUE THREAD

**Issue by montaguethomas** [Maks3w/FR3DLdapBundle#106]
I've implemented FR3DLdapBundle with FOSUserBundle into my application without issue. But I have expectations that the application could be used without ldap and just local auth via FOSUserBundle.

As far as I can tell and have tested, there is no way to disable ldap auth from the config. Additionally, it looks like requirement checks, such as php-ldap extension, would be triggered regardless of a config since it's in the bundle boot method.

Any plans to better support a config based enabled setting?

**Comment by Maks3w** [comment]
Sorry but I don't understand your point

**Comment by montaguethomas** [comment]
I've added the FR3DLdapBundle to my application which enabled ldap support and requires a fr3d_ldap config block with a driver.host set. But say if my end user doesn't which to use ldap support. There is no way to disable trying to preform ldap lookups or authentication. Additionally, you must supplying a driver.host config that isn't null. Also if you do set it to something else like localhost it fails to connect and throws an error.

Well I now stand corrected. After writing that up, I thought about the fr3d_ldap security firewall setting. Adding a new param and setting the fr3d_ldap to use it provides this functionality, though they still have to set driver.host to something non-null, which is fine.

**Comment by Maks3w** [comment]
Sorry but this is the way of Symfony works. User providers and authentication are two different phases.

You can use this bundle for either retrieve a user from LDAP, authenticate any user against LDAP or both at the same time.

If you don't need LDAP then I don't understand why you need this bundle.

**Comment by felicitus** [comment]
I have the same issue. I'm the developer of [PartKeepr](http://www.partkeepr.org). My application should be configurable for the end user, so if the user wants LDAP authentication, he should be able to configure it. Out of the box, no LDAP authentication is required.

**Comment by montaguethomas** [comment]
@Maks3w the need for the bundle is some installs of my application may not use ldap auth. 

@felicitus I found that setting the security firewall setting for fr3d_ldap to false seems to work to prevent usage of the ldap bundle, even when completely configured or configured with example data. Take a look at this gist for an example: https://gist.github.com/montaguethomas/b0067afe135012c14363.

**Comment by Maks3w** [comment]
I'll close this because IMO this is out of the scope of the bundle. Any PR is welcome.
