### ISSUE TITLE
Reliance on the Form Login authentication listener means that the DaoAuthenticationProvider is used for no reason

### ISSUE THREAD

**Issue by bkosborne** [Maks3w/FR3DLdapBundle#109]
It seems this bundle (I'm using 2.x dev) relies on the authentication listener `UsernamePasswordFormAuthenticationListener` ( https://github.com/Maks3w/FR3DLdapBundle/blob/master/Security/Factory/FormLoginLdapFactory.php#L55). Because of that, to get this bundle working, you have to add `form_login` as an auth provider in your security config, like so:

```
...
    firewalls:
        main:
            fr3d_ldap: ~
            form_login: ~
            anonymous: ~
...
```

Otherwise configuration information that the `UsernamePasswordFormAuthenticationListener` needs is not available (it's never loaded by service container).

But the side effect is that when a security token is being authenticated, it will try and authenticate first with the LDAP provider (`LdapAuthenticationProvider`) - but if that fails, it then tries to authenticate the token with `DaoAuthenticationProvider`. This seems broken to me, isn't it? Why do we need to attempt authentication with that provider at all? I wonder if there's a better way to use the `UsernamePasswordFormAuthenticationListener` without registering the `DaoAuthenticationProvider`?

**Comment by Maks3w** [comment]
`DaoAuthenticationProvider` is used for native FOSUserBundle entities. Also this bundle **don't remove** any authenticator already registered, this bundle **add** a custom authenticator for the specific LDAP logic.

**Comment by bkosborne** [comment]
I'm trying to use this bundle w/o using FOSUserBundle, and instead run it in a state where there the users are not stored locally at all. In this case, it's not necessary to use `DaoAuthenticationProvider`. Maybe I can see about removing it...

**Comment by Maks3w** [comment]
That is something do symfony not this bundle. I can't do nothing
