### ISSUE TITLE
Manageing User

### ISSUE THREAD

**Issue by roberteikermann** [Maks3w/FR3DLdapBundle#11]
Hi,
I think there should be a possibebility  to manage the users in the ldap server. If a user in FosUserBundle is created, deleted or modified, something should reflect that in the ldap server.

I don't know how to do that exactly. Maybe one could write a new UserManager the extends the FosUserManager and forwards the method calls to the FosUserManager but additionally calls a ldapUserManager to update the data in the ldap server.

another possebility could be, to let the FosUsermanager throw events on UserChange, UserCreate, UserDelete and a ldapUsermanager could listen for that and update the ldap data.

**Comment by Maks3w** [comment]
I'll close this proposal because the currency UserManager will disappear on 3.0.x.

However if anyone wants add new features in LdapManager he/she will be welcome.
