### ISSUE TITLE
Adding user with fos:user:create and dn required when INSERTing

### ISSUE THREAD

**Issue by webdevilopers** [Maks3w/FR3DLdapBundle#111]
Doing my first steps with this bundle. Guess this is Kind of stupid question and I am just missing a config.

I'm using the `php app/console fos:user:create` command and can't INSERT because I get `Column 'dn' cannot be`.
Looking at the provided entities `dn` is not `nullable`. So I guess there is some automatic process that is providing the Content of the column. Or is it not possible to use the command any more when using this bundle?

Possibly related issues:
- https://github.com/Maks3w/FR3DLdapBundle/issues/98
- https://github.com/Maks3w/FR3DLdapBundle/issues/31
- https://github.com/Maks3w/FR3DLdapBundle/issues/10

**Comment by Maks3w** [comment]
Implementation of `LdapUserInterface` is optional and implementation is free. There is no limits in this.

**Comment by webdevilopers** [comment]
Sorry @Maks3w , I'm not getting it. Normally when using this bundle with `FosUser` are the console command for promoting supposed to work?

Or do I have to persist `dn` by myself like @tcowin did in his example?
https://github.com/Maks3w/FR3DLdapBundle/issues/10#issuecomment-8749903

**Comment by Maks3w** [comment]
Don't implement the interface.

**Comment by webdevilopers** [comment]
Got it! Thanks! So the Interface should actually be used when adding users via Administration Panel or similar instead of the fos command line I guess.

**Comment by Maks3w** [comment]
All your guesses are wrong. Because its optional, just don't implement optional things make your system fail. Simple law of computer science.

**Comment by webdevilopers** [comment]
I understand you feel disturbed by questions of people beginning with your bundle.
But no need to make them feel it that way.

I had a concrete technical question and got a general advice about Computer science. I guess you are having a bad day - that's all.

This is a great bundle and you should feel happy that so many people are using it.

Thanks for your help anyway! :+1:
