### ISSUE TITLE
is there a version relating to develop?

### ISSUE THREAD

**Issue by ctrl-f5** [Maks3w/FR3DLdapBundle#114]
I've been working with the develop branch of this repo in my project. Now I wanted to switch it to a more stable version, but all existing tags have other configuration requirements?

Am I missing something or is develop so much ahead that there isn't a version for it yet? Maybe it would be nice to add a branch alias to 3.0 to composer.json on develop?

**Comment by Maks3w** [comment]
At this moment I don't have plans for continue the development. IIRC SF 2.8 includes a builtin LDAP authenticator so this repo will be useless soon (It's still usefull for those who need a better compatibility layer with different directory providers)

**Comment by Maks3w** [comment]
V3 has been released
