### ISSUE TITLE
[SUGGEST] Create a user interface to implement some basic methods 

### ISSUE THREAD

**Issue by cirovargas** [Maks3w/FR3DLdapBundle#116]
On the LdapManager (hydrate method) are called some methods on the user class (setPassword,setEnabled,setDn).

My user class dont have this methods because i'm not using the fosuserbundle.

To prevent erros we can do a interface to implement and validate if user class implement this or the fosuserbundle abstract.

What do you thing?

**Comment by Maks3w** [comment]
Develop branch contains the concept of Hydrator classes so it can be easily customized without override the LdapManager.
