### ISSUE TITLE
[Documentation] Hydrator typo?

### ISSUE THREAD

**Issue by xDaizu** [Maks3w/FR3DLdapBundle#122]
In the [hydrator cookbook](https://github.com/Maks3w/FR3DLdapBundle/blob/master/Resources/doc/cookbook/custom_hydrator.md) the code reads:

```php
// src/Acme/DemoBundle/Ldap/UserHydrator.php
<?php

namespace Acme\DemoBundle\Ldap;

use FR3D\LdapBundle\Hydrator\HydratorInterface;
use Symfony\Component\Security\Core\User\UserInterface;

class LdapManager implements HydratorInterface
{
    /**
     * Populate an user with the data retrieved from LDAP.
     *
     * @param array $ldapUserAttributes
     *
     * @return UserInterface
     */
    public function hydrate(array $entry)
    {
        $user = new \Acme\DemoBundle\Entity\User();
        $user->setUsername($ldapUserAttributes['uid'][0]);
        $user->setEmail($ldapUserAttributes['email'][0]);

        return $user;
    }
}
```

where the `@param` field, the actual parameter `$entry` and the argument inside the function `$ldapUserAttributes[...]` have inconsistent naming :sweat_smile: 

Also, I can't find the class `FR3D\LdapBundle\Hydrator\HydratorInterface;`, is it deprecated or I'm just blind?

**Comment by Maks3w** [comment]
About the 2nd. Yep, you may blind https://github.com/Maks3w/FR3DLdapBundle/blob/master/Hydrator/HydratorInterface.php

About the 1st. Fixed https://github.com/Maks3w/FR3DLdapBundle/commit/ba7a62b5610f1702a719a91580146c5d9553cecc

**Comment by xDaizu** [comment]
@Maks3w ...sorry, but I can't find that file anywhere in the vendor/fr3d/ldap-bundle/ folder...
Using ` "fr3d/ldap-bundle": "2.0.*@dev" `as the [docs](https://github.com/Maks3w/FR3DLdapBundle/blob/master/Resources/doc/index.md) say.


![fr3d](https://cloud.githubusercontent.com/assets/7584835/13352623/bd97d6ea-dc8e-11e5-96b7-bcba408226d8.png)

**Comment by Maks3w** [comment]
v3 is the current version

**Comment by xDaizu** [comment]
If the version of the documentation is 3.0, put it in the installation
snippet, plz! :)
