### ISSUE TITLE
Dump FOS requirement

### ISSUE THREAD

**Issue by RonanL** [Maks3w/FR3DLdapBundle#125]
Hi,

I use this bundle with a custom hydrator since I don't use FOSUserBundle, but the LegacyHydrator service still requires a fos_user.user_manager service to exist.
I declared a dummy service with this name, but it would be nice if it wasn't required.

**Comment by Maks3w** [comment]
You don't have to use LegacyHydrator, copy the code you need in your own custom hydrator.

**Comment by RonanL** [comment]
The problem is that even if you don't use it, symfony still try to build dependencies.

**Comment by Maks3w** [comment]
What is the value of this config setting `fr3d_ldap.service.user_hydrator`?

**Comment by Dragnucs** [comment]
@Maks3w please explicitly clarify in the documentation that one should make use of his own custom hydrator.
