### ISSUE TITLE
How to create a custom attributes on ldap server running on ubuntu debian server?

### ISSUE THREAD

**Issue by dotjose** [Maks3w/FR3DLdapBundle#126]
Hi there, I have been working on LDAP Server running on Ubuntu Debian package and I need to extend the LDAP default schema to add my own attribute fields like preferred language, gender, ...etc. Is that possible?

with warmest regards

**Comment by Dragnucs** [comment]
This is out of the scope of this bundle. But it is normally possible. You need to see the documentation related to the server you are using and find out how you can modify the schema there.
