### ISSUE TITLE
Drop Zend LDAP in favor of Symfony LDAP

### ISSUE THREAD

**Issue by Dragnucs** [Maks3w/FR3DLdapBundle#135]
Now Symfony has its own [LDAP](https://symfony.com/components/Ldap) component cofficially released since 2.8, do you plan in dropping the Zend dependency in favor of Symfony one?

[Documentation is available](https://symfony.com/doc/current/components/ldap.html).

**Comment by Maks3w** [comment]
There is no reason for to change something it works. Also Zend LDAP has more features and compatibility with more systems.
