### ISSUE TITLE
Set user Role depending Ldap group membership

### ISSUE THREAD

**Issue by ikerib** [Maks3w/FR3DLdapBundle#138]
Hi,
I have this bundle installed and configured with FOSUserBundle and it works really good. Thanks!!

Whats I need now is to assign different ROLES depending witch ldap ther user is member.
for instance, if the user in LDAP is member of the group "Administrators" it has to have ROLE_ADMIN, or if is member of LDAP group "AppAdmin" it has to have "ROLE_MANAGER" otherwise "ROLE_USER".

How can I achieve that? Any clue?
Thanks in advance

**Comment by CoalaJoe** [comment]
Use this:
![image](https://cloud.githubusercontent.com/assets/5689499/24442492/b04bbc14-145e-11e7-849b-817df7f96760.png)

`- { ldap_attr: memberof, user_method: addLdapGroup }`

Then, use an eventlistener on the user-entity to check if he has been created, and map the ldapGroups to roles.

**Comment by ikerib** [comment]
yes, I've done it with it, thanks anyway! I forgot to close this issue
