### ISSUE TITLE
override FR3DLdapBundle

### ISSUE THREAD

**Issue by SahnounM91** [Maks3w/FR3DLdapBundle#144]
HI,

I've installed and configured FR3DBundle with FOSUserBundle and everything works OK , but there is something that I do not understand, why FR3DLdpaBundle save users in the database without password ? when I'm trying to Login the second time, two situations come to me : if the order of the chain providers is : ` providers: [fr3d_ldapbundle,fos_userbundle ]` : FR3DLdapBundle trying to insert the same user another time in the database (duplicated entry) !
 when the order of the chain providers is :
 ` providers: [fos_userbundle,fr3d_ldapbundle ]` : the error invalid credential appear to me cause in the first login the user saved without password in the database.
 So I'm asking is there any way to hack the Bundle and override some controllers and functionality to get login functionality work successfully?
@Maks3w

**Comment by patrick-mota** [comment]
A bit late but you can probably use custom hydrator to implement something. Check the faq in fr3d/ldap-bundle/Resources/doc/cookbook/custom_hydrator.md
