### ISSUE TITLE
Support of Symfony 3

### ISSUE THREAD

**Issue by edrush** [Maks3w/FR3DLdapBundle#152]
Hi,

does anyone have FR3DLdapBundle running with Symfony 3? We don't get it working, since the last release was 2016 maybe it's just not supported? We always end up in the DaoAuthenticationProvider, see my [first issue](https://github.com/Maks3w/FR3DLdapBundle/issues/151).

Thank you, any help would be appreciated! Do you know any package is supporting Ldap in Symfony 3?

**Comment by jenszahner** [comment]
We are using it in a Symfony 3.4.8 project without problems.

**Comment by edrush** [comment]
All right, thank you! We switched to https://github.com/ldaptools/ldaptools, as there was no feedback to this and another issue for some weeks.

Regards!
