### ISSUE TITLE
Fatal error on login with invalid credentials

### ISSUE THREAD

**Issue by slaci** [Maks3w/FR3DLdapBundle#155]
In the following commit: https://github.com/Maks3w/FR3DLdapBundle/commit/7fa26a80e0d69697dec6b9f5638b2d7f7ba60991#diff-15c4a1b6b35707234841ab858b03ee8c `zendExceptionHandler()` requires a `$password` second parameter, but the [`search()`](https://github.com/Maks3w/FR3DLdapBundle/blob/master/Driver/ZendLdapDriver.php#L59) function uses the same function with only 1 parameter.

This triggers the following fatal error on login with invalid credentials: `Type error: Too few arguments to function FR3D\LdapBundle\Driver\ZendLdapDriver::zendExceptionHandler(), 1 passed`

The `$password` parameter should be optional.

**Comment by Maks3w** [comment]
PRs are welcome
