### ISSUE TITLE
Stable tag for 2.0.0

### ISSUE THREAD

**Issue by iltar** [Maks3w/FR3DLdapBundle#51]
Hey,

Is it possible to release tag 2.0.0? I've been using the bundle for quite a while but I'm not happy having to use 2.0.*@dev in every project. My current situation is that I have a bundle with a dependency on this bundle, but due to having it in @dev, means I have to add not only my bundle, but also this project.

I have no idea if there will be any progress on this bundle soon, but after 8 months I would like to see a stable release ;)

Iltar

**Comment by Maks3w** [comment]
Stable tag has been released now. Sorry for the delay.
