### ISSUE TITLE
Add possibility for many LDAP domains

### ISSUE THREAD

**Issue by renoirb** [Maks3w/FR3DLdapBundle#6]
I am in a situation where I need to authenticate with many LDAP servers and be able to choose at least ONE of them.

Using your work I managed to extend and inject the different servers. I will gladly share, I have a blog post incubating about it.

But my question remains.  I need to be able for the user to choose the LDAP server that they know to use.

More details:
- Implementing FOSUserBundle
- chain_provider list with a collection of providers from the bundle extending FR3DLdapBundle (fos_userbundle being first)
  
  ```
  providers:
      chain_provider:
          providers: [ fos_userbundle, client_domain1, client_domain2, client_domain3 ]
  ```

Do you have any hints about how to do this?

My feature implementation work, but I know my client will ask that the domain selection to /actually work/.

Note:
- I looked at overriding Security controller thing, and find it not clean.
- I created a `InteractiveLoginEvent` listener and tried with `OpenSkyRuntimeConfigBundle`, but not sure how clean it is... and where to give that parameter bag. 

So, I ended up using the advantage of the chain provider... I am missing something. and I'd like some pointers.

Thanks :)

**Comment by vlad88sv** [comment]
Excuse that I'm not well versed on this, but the #45 is merged into Fr3dLdapBundle? What I mean to ask is: can I use multiple LDAP servers in current dev-master or do I have to merge in my local vendor lib the patch before using that feature?

**Comment by DarwinOnLine** [comment]
Unfortunatly not, I have created my own bundle basing on these bundle, for
my own purposes...
Le 13 janv. 2015 14:52, "Vladimir Hidalgo" <notifications@github.com> a
écrit :
