### ISSUE TITLE
Second login attempt error INSERT INTO

### ISSUE THREAD

**Issue by encryptedfear** [Maks3w/FR3DLdapBundle#64]
Hello,

Here's the overview of the problem.

My first login attempt, the result is OK. I logout.
I login again, an error occurs.

An exception occurred while executing 'INSERT INTO fos_user().

[1/2] PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'username' for key 'UNIQ_957A647992FC23A8'

[2/2] DBALException: An exception occurred while executing 'INSERT INTO fos_user () 

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'username' for key 'UNIQ_957A647992FC23A8' 

Is it normal for it to do an SQL command of INSERT every time I login?

Running on Symfony 2.4.3, FR3DLdapBundle 2.0.x.

Thanks in advance.

**Comment by SahnounM91** [comment]
hey @encryptedfart I think FR3DLdapBundle fetch users from ldap directory and insert it in the database without the password , so if you change the order of your providers you will find another  problem when you login, kind of "invalid credential " !!
