### ISSUE TITLE
Incompatibility with Symfony 2.6

### ISSUE THREAD

**Issue by mbyta** [Maks3w/FR3DLdapBundle#79]
Hi everyone,

I must use Symfony 2.6 for my current project but I need to install the FR3DLdap bundle.
When installing it, I get this error message: "fr3d/ldap-bundle 1.5.2 requires symfony/security-bundle 2.0.* . Installation failed !"

Is there a workaround for this ?

Thanks

**Comment by Maks3w** [comment]
use 2.0 branch

**Comment by mbyta** [comment]
It works !

Thanks a lot Maks3w
