### ISSUE TITLE
Don't create a user on the first ldap authentification

### ISSUE THREAD

**Issue by wonzbak** [Maks3w/FR3DLdapBundle#81]
Hello,

First of all this bundle is a great job.

But I would try a new wokflow on authentification:
I would like to not persist a user on the first authentification. 
eg:
    1. the user don't exist in the database -> login fail.
    2. I create the user "manualy" in an admin interface and affect roles.
    3. the user can log in via ldap (only if he exists in the database).

The idea is to authorize only users which have at least a  role.
Is there a simple way to achieve that?

**Comment by Maks3w** [comment]
Try removing the user provider part.

**Comment by jrojat** [comment]
Hello,

I want to use this workflow too. 

Can you help me to understand how to establish this configuration ?

Thank's in advance.
