### ISSUE TITLE
Always same error login Binding requires username in DN form

### ISSUE THREAD

**Issue by titom59280** [Maks3w/FR3DLdapBundle#84]
Hello Everyone,

I use this bundle to connect my users with the ldap I think I have the correct configuration but when I tried to connect a user I have every time the same error :
 ldap_driver.DEBUG: Binding requires username in DN form

I really don't know why I have this error if anyone can help me it will be great.

Here's my configurations config.yml :
fr3d_ldap:
    driver:
        host:   server ipAdress
        port:         389    # Optional
        username:     SomeUser@domain.something    # Optional
       password:         # Optional
        bindRequiresDn:        true
        accountFilterFormat: (&(uid=%s))
        useSsl:       false   # Enable SSL negotiation. Optional
    user:
        baseDn: CN=Users,DC=domain,DC=something
        filter: (&(ObjectClass=user))
        attributes:          # Specify ldap attributes mapping [ldap attribute, user object method]
           - { ldap_attr: uid,  user_method: setUsername } # Default

security.yml :
firewalls:
        main:
            pattern: ^/
            fr3d_ldap: ~
            form_login:
                provider: chain_provider #fos_userbundle
                csrf_provider: form.csrf_provider
                always_use_default_target_path: true
                default_target_path: true
            logout: true
            anonymous: true
providers:
    fr3d_ldapbundle:
        id: fr3d_ldap.security.user.provider

Thank you for your help

**Comment by Maks3w** [comment]
`username` setting is not written in DN way.

**Comment by titom59280** [comment]
I don't think I understand correctly could you explain me a little bit more about this issue

**Comment by Maks3w** [comment]
`SomeUser@domain.something` should be something like `cs=SomeUser@domain.something,ou=xxxx

**Comment by titom59280** [comment]
OK I will try it tomorrow

**Comment by titom59280** [comment]
Thanks a lot

**Comment by titom59280** [comment]
Hello I tried with this line :
'username:     cn=SomeUser@SomeDomain.something,ou=Some ou

But I have this error this time :
'Operations error; 000004DC: LdapErr: DSID-0C0906E8, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v1db1): searching:

What did I do wrong?

**Comment by titom59280** [comment]
I think a almost reach my goal.
When I set username like this :
 username:     cn=SomeUser,OU=Users,DC=SomeDomain,DC=something
 password:   somePassword
 - { ldap_attr: cn,  user_method: setUsername } # Default

I get this error : 
Invalid credentials; 80090308: LdapErr: DSID-0C0903A9, comment: AcceptSecurityContext error, data 52e, v1db1

I think it means that the password/credential is invalid doest it?

But I'm sure the password in my login form it's good so what can I do in order to prevent this error.

**Comment by titom59280** [comment]
I have something here I changed the ou=Users by ou=someOU and when I try to log in in the log I see that SomeUser is found on ldap But I Have a error :
Authentication request failed: Bad credentials.

But I don't know how to handl with this error

**Comment by titom59280** [comment]
Still no answer I'm desperate to find a solution for this problem
