### ISSUE TITLE
UserAuthentificationProvider is used instead of LdapAuthentificationProvider

### ISSUE THREAD

**Issue by titom59280** [Maks3w/FR3DLdapBundle#85]
Hello I used this bundle with the 2.0 branch but I have a problem,

When I debug my app I see that UserAuthentificationProvider of Symfony/core before the LdapAuthentificationProvider of FR3DLdap that means that the username and password are not binded.

here my config.yml:

fr3d_ldap:
    driver:
        host:   SomeIP
        port:         389    # Optional
         #username:     %ldap.driver.username% #cn=SomeCN,OU=SomeOU,DC=SomeDC,DC=fr  # Optional
       #password:     %ldap.driver.password% #somePassword    # Optional
        bindRequiresDn:        true
        accountFilterFormat: (&(samaccountname=%s))
       #optReferrals: false  # Optional
       #useSsl:       false   # Enable SSL negotiation. Optional
       #useStartTls:  true   # Enable TLS negotiation. Optional
    user:
        baseDn: ou=SomeOU,DC=SomeDC,DC=fr
        filter: (&(ObjectClass=Person)(uid=%s))
        attributes:          # Specify ldap attributes mapping [ldap attribute, user object method]
           - { ldap_attr: uid,  user_method: setUsername } # Default
           - { ldap_attr: cn, user_method: setName }
           #- { ldap_attr: name,  user_method: setPassword }
           - { ldap_attr: mail,   user_method: setEmail }     # Optional
           #- { ldap_attr: userPrincipalName,  user_method: setPassword }         # Optional
    service:
        #user_manager: fos_user.user_manager          # Overrides default user manager
        ldap_manager: fr3d_ldap.ldap_manager.default # Overrides default ldap manager'

And here my security.yml:
security:
    access_decision_manager:
            # Strategy can be: affirmative, unanimous or consensus
            strategy: unanimous # Vote the user if don't have all roles required.
    encoders:
        #FOS\UserBundle\Model\UserInterface: sha512
        #DUPONT\UserBundle\Entity\User: sha512
        DUPONT\UserBundle\Entity\User: sha512

    # http://symfony.com/doc/current/book/security.html#hierarchical-roles
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        chain_provider:
            chain:
                providers: [fr3d_ldapbundle, fos_userbundle]
        fr3d_ldapbundle:
            id: fr3d_ldap.security.user.provider
        fos_userbundle:
            id: fos_user.user_manager

    # the main part of the security, where you can set up firewalls
    # for specific sections of your app
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            fr3d_ldap: ~
            form_login:
                provider: chain_provider #fos_userbundle
                csrf_provider: form.csrf_provider
                always_use_default_target_path: true
                default_target_path: /
            logout: true
            anonymous: true
        secured_area:
            pattern: ^/
            form_login:
                check_path: /login_check
                login_path: /login
            logout:
                path: /lougout
        login_firewall:
            pattern: ^/login$
            anonymous: ~

    # with these settings you can restrict or allow access for different parts
    # of your application based on roles, ip, host or methods
    # http://symfony.com/doc/current/cookbook/security/access_control.html
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
My question is what can I do to make the LdapAuthentificationProvider call before UserAuthentificationProvider or to not call this last one.

Thanks for your help

**Comment by Maks3w** [comment]
May you should check what firewall are you using. I see a bit of mess there, main and secured_area share the same pattern.

**Comment by titom59280** [comment]
Hello I use the main :
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: DUPONT\userBundle\Entity\User

Did I have to add the firewall name in the fr3d_ldap as well.

I added secured_area because when I search on every doc in the internet I try everything possible but without success so far

**Comment by titom59280** [comment]
I think I have a new piece of information I have in my User class which extend of the User of the FOSUserBundle witch in my opinion call the UserAuthentificationProvider So I test without this extension this time UserAuthentificationProvider is not called But I think that the checkAuthentication function of the LdapAuthentificationProvider is never called even with the UserAuthentificationProvider called so :
  $this->ldapManager->bind($currentUser, $currentUser->getPassword() is therefore not call either.

Do I'm mistaken so far?

So What can I do in order to call this last code line?

**Comment by titom59280** [comment]
Is it normal that in hydrate function of LdapManager class there is this line :
  $user->setPassword('');
Because what I can see when I debug it's when I'm in isPasswordValid function of PlaintextPassword class the user->getPassword is empty so it return false and therefore I Have a bad credential exceptions.

Does the password does not have to be set with the $token->getCredentials somewhere or with the $salt in order to have a match.

Thanks for your reply

**Comment by Maks3w** [comment]
that field is mandatory by FOS IIRC

**Comment by titom59280** [comment]
Ok I understand but you agreed that this is the reason why I have a bad credentials exception.

So What can I do overide this LdapManager?

**Comment by Maks3w** [comment]
I don't guess that is the reason. You shouldn't to have a difficult setup. IMO you did so many changes is difficult to know what is failing.

My suggestion. Start from a clean symfony project. Test the login works and the continue with the rest of your project.

**Comment by titom59280** [comment]
My symfony project is almost empty except for FosUserBundle, FR3DldapBundle and two bundle for create pdf and excel document.

 I think that my setup is the same that every doc i could have read because I can log in with a user in database and when I tried with a user from the ldap my user is well found on ldap but now I have this error of bad credentials and I don't know how to correct it.

I tried last friday to start anew but always the same problem.

**Comment by titom59280** [comment]
My question is maybe a little weird or dumb but when the user is found on ldap what does the bundle do : log in, create a new user in database, check the couple (password username).

I know I can be a little annoying but That almost a week I'm with the bundle and I can make it works so now I don't know what to do. Sorry again

**Comment by Maks3w** [comment]
Nothing.

SF has two different steps on the authentication process.

1) Retrieve the user (UserProvider)
2) Authenticate (Use the user as argument for the AuthenticationProvider and bind to LDAP)

So the user used in Authentication is decoupled from the provider.

You can retrieve users from BD and authenticate against LDAP, viceversa, or both the same

**Comment by titom59280** [comment]
So if I understood correctly the exception of bad credential depends of the authentificationProvider of symfony and not of your bundle because it "has done his job in finding the user on the ldap"

**Comment by Maks3w** [comment]
The authentication provider throws the exception, but not exactly that one. SF has a switch for hide sensitive security info in a generic message.

https://github.com/Maks3w/FR3DLdapBundle/blob/2.0.x/Security/Authentication/LdapAuthenticationProvider.php#L35
https://github.com/Maks3w/FR3DLdapBundle/blob/2.0.x/Security/Authentication/LdapAuthenticationProvider.php#L88

**Comment by titom59280** [comment]
Ok I don't know what to do next yet but I understood better the whole thing
