### ISSUE TITLE
Add support for unauthorized anonymous authentication

### ISSUE THREAD

**Issue by dbaq** [Maks3w/FR3DLdapBundle#9]
Hi all,

On a previous project, I needed to authenticate users through AD. But the server did not accept anonymous authentication and I could not let an user account in the configuration file. To solve this issue, I have changed the authentication logic.

New authentication logic:
1- Directly, checking user authentication with the bind method
2- if ok, retrieving and hydrating the user object
2bis- if nok, return false without any data searched

Would it be better to switch the retrieving phase and the checking authentication phase?

**Comment by younessadmi** [comment]
Hello,
Is there any news ?
