### ISSUE TITLE
Authentication request could not be processed due to a system problem.

### ISSUE THREAD

**Issue by AurasCy** [Maks3w/FR3DLdapBundle#92]
Hi everybody and I m sorry if the question is dumb. I am very new with Symfony (2.6) and my first project requires the User to authenticate from AD. 

Whatever I do I am keep getting: Authentication request could not be processed due to a system problem.

*security.yml*

    security:
    # http://symfony.com/doc/current/book/security.html#encoding-the-user-s-password
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    # http://symfony.com/doc/current/book/security.html#hierarchical-roles
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
            chain_provider:
                chain:
                    providers: [fos_userbundle, fr3d_ldapbundle]

            fr3d_ldapbundle:
                id: fr3d_ldap.security.user.provider

            fos_userbundle:
                id: fos_user.user_provider.username

    # the main part of the security, where you can set up firewalls
    # for specific sections of your app
    firewalls:
        main:

            pattern:    ^/
            fr3d_ldap:  ~
            form_login:
    #            check_path: fos_user_security_check
    #            login_path: fos_user_security_login
                always_use_default_target_path: true
                default_target_path: /main
                provider: chain_provider
            logout:
                path:   fos_user_security_logout
                target: /login
            anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    # with these settings you can restrict or allow access for different parts
    # of your application based on roles, ip, host or methods
    # http://symfony.com/doc/current/cookbook/security/access_control.html
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }

*config.yml*

    fr3d_ldap:
    driver:
        host:                192.168.137.200
        port:                50000
        username:            DOMAIN\Admnistrator    # Optional
        password:            pass_here    # Optional

    user:
        baseDn: OU=HP,OU=MANA,DC=DOMAIN,DC=com
        filter: (&(ObjectClass=Person))
        attributes:          # Specify ldap attributes mapping [ldap attribute, user object method]
               - { ldap_attr: uid,  user_method: setUsername }
               - { ldap_attr: mail, user_method: setEmail }

and my *Entity/User* class

    /**
    * @ORM\Entity
    * @ORM\Table(name="mdr_user")
    */
    class User extends BaseUser implements LdapUserInterface
    {
    /**
    * @ORM\Id
    * @ORM\Column(type="integer")
    * @ORM\GeneratedValue(strategy="AUTO")
    */
    protected $id;
    
    /**
     * @ORM\Column(type="string", nullable=true)
     */
    protected $name;

    /**
     * Ldap Object Distinguished Name
     * @ORM\Column(type="string", length=128)
     * @var string $dn
     */
    private $dn;

    public function __construct()
    {
        parent::__construct();
        if (empty($this->roles)) {
            $this->roles[] = 'ROLE_USER';
        }
    }

    public function setName($name) {
        $this->name = $name;
    }

    /**
     * {@inheritDoc}
     */
    public function setDn($dn)
    {
        $this->dn = $dn;
    }

    /**
     * {@inheritDoc}
     */
    public function getDn()
    {
        return $this->dn;
    }
    }

if I dont implement LdapUserInterface, the DB authenticates fine but always if I use anything else other than mysql entries I get that error. Can you please help me with that  ? 
Appreciate it.

**Comment by Maks3w** [comment]
Did you look the log?. Anyway ask in a Q&A site like stackoverflow.
