### ISSUE TITLE
Hydrator Injection wrong parameters?

### ISSUE THREAD

**Issue by Noles** [Maks3w/FR3DLdapBundle#95]
My "human" tests with the "new" hydration code doesn't work as expected.

Are you sure that on Hydrator.. class construct the correct parameters are injected!? When I use  %fr3d_ldap.ldap_manager.parameters% as defined in current develop branch I only got an error: Warning: Illegal string offset 'ldap_attr'

It seems that within the foreach in HydrateWithMapTrait:24 the $attr variable output is a string and returns the baseDn. I think the level we need is $config['user']['attributes'] and not $config['user'] which is mapped to %fr3d_ldap.ldap_manager.parameters%

Or have I missed something?

**Comment by Maks3w** [comment]
You are right. Fixed with a2c90fa
