### ISSUE TITLE
Why do I need to set Dn path in db

### ISSUE THREAD

**Issue by titom59280** [Maks3w/FR3DLdapBundle#98]
Hello, 

I'm sorry to disturb you again with some problems with this bundle but I wanted to know why I need to fill the dn path in the user table in DB.

I know it can be strange but if I don't set it no connexion is possible.

I have the line :
user:
        baseDn: OU=foo,OU=foo,OU=foo,OU=foo,DC=fr,DC=foo

but of what I can see, whatever informations I write these line is never used.

**Comment by Maks3w** [comment]
You don't need to persist the data. To have the DN optimize the time required to authenticate the user.

Basically along the authentication process there are 3 transactions against the LDAP directory.

1. Search if user exists and hydrate the user
2. Obtain the DN for perfom the binding later
3. Bind user credentials against the DN and password.


In the other side fr3d_ldap.user.baseDn it's an optimization for reduce the search in the LDAP. i.e. instead to do a full search along all the LDAP only perfom a search in a specific subtree.
